spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://127.0.0.1:${LOCAL_POSTGRES_PORT:5432}/${LOCAL_POSTGRES_DB:community}
    username: ${LOCAL_POSTGRES_USER:community_local}
    password: ${LOCAL_POSTGRES_PASSWORD}

  elasticsearch:
    uris: http://127.0.0.1:${LOCAL_ELASTICSEARCH_PORT:9200}

  jpa:
    show-sql: true

app:
  cors:
    allowed-origins:
      - http://127.0.0.1:5173
      - http://localhost:5173
